repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  # ---------------- PYTHON ----------------

  # ---------------- TERRAFORM ----------------
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
    # rev: v1.105.0 # Use the latest version
    # hooks:
      # - id: terraform_fmt       # Formats code to canonical style
        # Removed the 'files' line to let recursive mode handle it
        # args:
          # - --args=-recursive # Force scanning of all subfolders
          # - --hook-config=--tf-path=tofu
      # - id: terraform_validate  # Checks for syntax and logic errors
        # This tells the hook to look into the terraform folder specifically
        # args:
        #   - --args=-json
        #   - --init-args=-backend=false
        #   - --hook-config=--tf-path=tofu
        #   - --hook-config=--retry-once-with-cleanup=true
      # - id: terraform_tflint    # Lints for provider-specific issues
        # args:
          # - --args=--recursive # TFLint also needs a recursive flag for subfolders
      # - id: terraform_docs      # Auto-generates README documentation
        # args:
          # - terraform/
      # - id: terraform_trivy     # Scans for security vulnerabilities
        # args:
          # - trivy config . --severity HIGH,CRITICAL
      # - id: terraform_checkov

  # ---------------- OPENTOFU (TOFU) ----------------
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.4.2 # Use latest compatible version
    hooks:
      - id: tofu_fmt
        args:
          - --args=-recursive
      - id: tofu_validate
        args:
          - --args=-json
          - --init-args=-backend=false
          - --init-args=-upgrade=false
      - id: tofu_tflint
        args:
          - --args=--recursive
      - id: tofu_docs
        args:
          - terraform/

  # ---------------- DOCS (MKDOCS) ----------------
  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs build check
        entry: mkdocs build #--strict
        language: system
        pass_filenames: false
        types: [markdown]
